# Jekyll configuration for GitHub Pages
# This enables markdown processing for documentation

# Site settings
title: "Instagram Unfollow Tracker"
description: "Free Instagram unfollow tracker - analyze your followers and following"
baseurl: "/instagram-unfollow-tracker"
url: "https://ignromanov.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Custom layout (no theme)

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Include files
include:
  - _redirects

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
