name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ===========================================
  # Build React Application
  # ===========================================
  build-app:
    name: Build React App
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Upload app artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: dist/
        retention-days: 1

  # ===========================================
  # Build Jekyll Documentation
  # ===========================================
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        
    - name: Setup Jekyll
      working-directory: ./docs
      run: |
        bundle install
        
    - name: Build Jekyll site
      working-directory: ./docs
      run: |
        bundle exec jekyll build -d ../dist/docs
        
    - name: Upload docs artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docs-build
        path: dist/docs/
        retention-days: 1

  # ===========================================
  # Deploy to GitHub Pages
  # ===========================================
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build-app, build-docs]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download app artifacts
      uses: actions/download-artifact@v4
      with:
        name: app-build
        path: dist/
        
    - name: Download docs artifacts
      uses: actions/download-artifact@v4
      with:
        name: docs-build
        path: dist/docs/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist